//! Generate `chiacheck/src/metrics/ast_type_map.rs` from `oxc_ast`'s generated `ast_kind.rs`.

use crate::util::workspace_root;
use anyhow::{Context, Result};
use cargo_metadata::{Metadata, MetadataCommand, Package};
use regex::Regex;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

pub fn run() -> Result<()> {
    let workspace_root = workspace_root()?;
    let (version, crate_root) = resolve_oxc_ast_sources(&workspace_root)?;

    let ast_kind_path = crate_root.join("src/generated/ast_kind.rs");
    let src = fs::read_to_string(&ast_kind_path)
        .with_context(|| format!("failed to read {}", ast_kind_path.display()))?;

    let ast_type_max = parse_ast_type_max(&src)?;
    let variants = parse_ast_type_variants(&src)?;

    anyhow::ensure!(
        variants.len() == ast_type_max as usize + 1,
        "AstType variant count {} does not match AST_TYPE_MAX + 1 (= {})",
        variants.len(),
        ast_type_max as usize + 1
    );

    let out_path = workspace_root.join("chiacheck/src/metrics/ast_type_map.rs");
    let contents = generate_file_contents(&version, &variants);

    if let Some(parent) = out_path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(&out_path, contents).with_context(|| format!("write {}", out_path.display()))?;

    run_rustfmt(&out_path)?;

    println!(
        "Wrote {} ({} variants, oxc_ast {})",
        out_path.display(),
        variants.len(),
        version
    );

    Ok(())
}

fn workspace_metadata(workspace_root: &Path) -> Result<Metadata> {
    MetadataCommand::new()
        .manifest_path(workspace_root.join("Cargo.toml"))
        .exec()
        .context("cargo metadata failed")
}

fn oxc_ast_package(metadata: &Metadata) -> Result<&Package> {
    metadata
        .packages
        .iter()
        .find(|p| p.name.as_str() == "oxc_ast")
        .context("package `oxc_ast` not found in cargo metadata")
}

/// Resolved `oxc_ast` version and crate root from workspace `cargo metadata` (same source as [`run`]).
fn resolve_oxc_ast_sources(workspace_root: &Path) -> Result<(String, PathBuf)> {
    let metadata = workspace_metadata(workspace_root)?;
    let pkg = oxc_ast_package(&metadata)?;
    let crate_root = pkg
        .manifest_path
        .parent()
        .context("oxc_ast manifest_path has no parent")?
        .as_std_path()
        .to_path_buf();
    Ok((pkg.version.to_string(), crate_root))
}

fn parse_ast_type_max(src: &str) -> Result<u8> {
    let re = Regex::new(r"(?m)^\s*pub const AST_TYPE_MAX:\s*u8\s*=\s*(\d+)\s*;")?;
    let caps = re
        .captures(src)
        .context("AST_TYPE_MAX not found in ast_kind.rs")?;
    Ok(caps[1].parse()?)
}

fn parse_ast_type_variants(src: &str) -> Result<Vec<(String, u8)>> {
    let re = Regex::new(r"^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(\d+)\s*,?\s*(?://.*)?$").unwrap();

    let start_marker = "pub enum AstType";
    let start = src
        .find(start_marker)
        .context("`pub enum AstType` not found")?;
    let after_marker = &src[start + start_marker.len()..];
    let brace_rel = after_marker
        .find('{')
        .context("`{` after AstType not found")?;
    let body_start = start + start_marker.len() + brace_rel + 1;

    let mut depth = 1u32;
    let mut end = None;
    for (idx, ch) in src[body_start..].char_indices() {
        match ch {
            '{' => depth += 1,
            '}' => {
                depth -= 1;
                if depth == 0 {
                    end = Some(body_start + idx);
                    break;
                }
            }
            _ => {}
        }
    }
    let end = end.context("unclosed AstType enum body")?;
    let body = &src[body_start..end];

    let mut variants = Vec::new();
    for line in body.lines() {
        let trimmed = line.trim();
        if trimmed.is_empty() || trimmed.starts_with('#') {
            continue;
        }
        if let Some(caps) = re.captures(trimmed) {
            let name = caps[1].to_string();
            let disc: u8 = caps[2].parse()?;
            variants.push((name, disc));
        }
    }

    anyhow::ensure!(!variants.is_empty(), "no AstType variants parsed");
    Ok(variants)
}

fn generate_file_contents(version: &str, variants: &[(String, u8)]) -> String {
    let mut arms = String::new();
    for (name, _) in variants {
        arms.push_str(&format!(
            "        \"{name}\" => Some(AstType::{name}),\n",
            name = name
        ));
    }

    format!(
        r#"// Generated by `cargo xtask gen-ast-type-map` from oxc_ast {version}.
// DO NOT EDIT. Regenerate after bumping the workspace `oxc_ast` version.

use oxc_ast::AstType;

/// Maps config tokens (variant names as used by oxc, e.g. `TSAnyKeyword`) to [`AstType`].
///
/// Regenerate via `cargo xtask gen-ast-type-map` after bumping `oxc_ast`.
pub fn ast_type_from_str(s: &str) -> Option<AstType> {{
    match s {{
{arms}        _ => None,
    }}
}}
"#,
        version = version,
        arms = arms
    )
}

fn run_rustfmt(path: &Path) -> Result<()> {
    let status = Command::new("rustfmt")
        .arg(path.as_os_str())
        .status()
        .context("failed to spawn `rustfmt` — install rustfmt (rustup component)")?;

    if !status.success() {
        anyhow::bail!("rustfmt exited with {}", status);
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_ast_type_max_finds_const() {
        let src = r"
/// docs
pub const AST_TYPE_MAX: u8 = 187;
";
        assert_eq!(parse_ast_type_max(src).unwrap(), 187);
    }

    #[test]
    fn parse_ast_type_max_errors_when_missing() {
        assert!(parse_ast_type_max("pub enum AstType { X = 0 }").is_err());
    }

    #[test]
    fn parse_ast_type_variants_extracts_discriminants() {
        let src = r#"
#[repr(u8)]
pub enum AstType {
    Program = 0,

    NullLiteral = 95, // trailing comment
    TSAnyKeyword = 187,
}
"#;
        let got = parse_ast_type_variants(src).unwrap();
        assert_eq!(
            got,
            vec![
                ("Program".to_string(), 0),
                ("NullLiteral".to_string(), 95),
                ("TSAnyKeyword".to_string(), 187),
            ]
        );
    }

    #[test]
    fn parse_ast_type_variants_errors_without_enum() {
        assert!(parse_ast_type_variants("pub const AST_TYPE_MAX: u8 = 1;").is_err());
    }

    #[test]
    fn parse_ast_type_variants_errors_when_no_variants() {
        let src = r"
pub enum AstType {
}
";
        assert!(parse_ast_type_variants(src).is_err());
    }

    #[test]
    fn ast_type_max_matches_variant_count_plus_one() {
        let src = r"
pub const AST_TYPE_MAX: u8 = 2;

pub enum AstType {
    A = 0,
    B = 1,
    C = 2,
}
";
        let max = parse_ast_type_max(src).unwrap();
        let variants = parse_ast_type_variants(src).unwrap();
        assert_eq!(variants.len(), max as usize + 1);
    }

    #[test]
    fn generate_file_contents_includes_version_and_match_arms() {
        let workspace_root = workspace_root().expect("xtask lives under workspace root");
        let (resolved_version, _) =
            resolve_oxc_ast_sources(&workspace_root).expect("cargo metadata resolves oxc_ast");

        let variants = vec![("Program".to_string(), 0), ("NullLiteral".to_string(), 95)];
        let out = generate_file_contents(&resolved_version, &variants);
        assert!(
            out.contains(&format!("from oxc_ast {resolved_version}.")),
            "banner should mention resolved semver"
        );
        assert!(out.contains("\"Program\" => Some(AstType::Program),"));
        assert!(out.contains("\"NullLiteral\" => Some(AstType::NullLiteral),"));
        assert!(out.contains("_ => None,"));
    }
}
